export const stock = [
    {
        id: 1,
        img: "https://www.mrcdinstrumentos.com.mx/shared/productos/20028/2910124568.jpg",
        nombre: "Guitarra Jackson JS Series Kelly JS32T",
        precio: "7337",
        stock: "10",
        category: "Guitarra_Electrica",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 2,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/e7889acd-0a84-40ad-a8e5-ebf9045f6530_548x548.jpg?v=1637316888",
        nombre: "Guitarra Yamaha Acústica F310P",
        precio: "4323",
        stock: "15",
        category: "Guitarra_Acustica",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 3,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/93f1a8bf-6d85-43fc-95cf-cd38dd13dbdb_548x548.jpg?v=1637278351",
        nombre: "Amplificador CODE412 MARSHALL",
        precio: "8070",
        stock: "20",
        category: "Amplificador",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 4,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/76053413-831d-4b50-b0b3-7d9c1d091f3d.jpg?v=1637292591",
        nombre: "Bateria MAPEX tornado 5 pzas  TND5254TCDR",
        precio: "13085",
        stock: "25",
        category: "Bateria",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {   
        id: 5,     
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 5",
        precio: "90",
        stock: "30",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 6,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 6",
        precio: "100",
        stock: "35",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 7,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 7",
        precio: "110",
        stock: "40",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 8,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 8",
        precio: "120",
        stock: "45",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 9,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 9",
        precio: "130",
        stock: "50",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 10,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 10",
        precio: "140",
        stock: "55",
        descripcion: "Esta es la descripcion de un objeto",
    },    
    {
        id: 11,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 11",
        precio: "150",
        stock: "60",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 12,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 11",
        precio: "160",
        stock: "65",
        descripcion: "Esta es la descripcion de un objeto",
    }

]