export const stock = [
    {
        id: 1,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 1",
        precio: "50",
        stock: "10",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 2,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 2",
        precio: "60",
        stock: "15",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 3,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 3",
        precio: "70",
        stock: "20",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 4,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 4",
        precio: "80",
        stock: "25",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {   
        id: 5,     
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 5",
        precio: "90",
        stock: "30",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 6,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 6",
        precio: "100",
        stock: "35",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 7,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 7",
        precio: "110",
        stock: "40",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 8,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 8",
        precio: "120",
        stock: "45",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 9,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 9",
        precio: "130",
        stock: "50",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 10,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 10",
        precio: "140",
        stock: "55",
        descripcion: "Esta es la descripcion de un objeto",
    },    
    {
        id: 11,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 11",
        precio: "150",
        stock: "60",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 12,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 11",
        precio: "160",
        stock: "65",
        descripcion: "Esta es la descripcion de un objeto",
    }

]