export const stock = [
    {
        id: 1,
        img: "https://www.mrcdinstrumentos.com.mx/shared/productos/20028/2910124568.jpg",
        nombre: "Guitarra Jackson JS Series Kelly JS32T",
        precio: 7337,
        stock: 10,
        category: "Guitarra_Electrica",
        descripcion: "La serie JS Kelly JS32 Tiene Un Cuerpo de álamo desplazado y Un mástil de Velocidad de arce atornillado con refuerzo de grafito Para Una Sólida Estabilidad Como una roca. Con 24 trastes jumbo e incrustaciones de aleta de tiburón nacaradas, el diapasón de amaranto Con Un Compuesto de radio de 12 - 16 Completamente encuadernado crea la superficie de juego ideales para riffs Gruesos y Acordes faciles cerca de la cejuela MIENTRAS SE aplana gradualmente en los Registros Superiores párrafo solos ultrarrápidos y curvas anchas sin miedo a inquietarse",
    },
    {
        id: 2,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/e7889acd-0a84-40ad-a8e5-ebf9045f6530_548x548.jpg?v=1637316888",
        nombre: "Guitarra Yamaha Acústica F310P",
        precio: 4323,
        stock: 15,
        category: "Guitarra_Acustica",
        descripcion: " YAMAHA F310P• Guitarra Acústica• Cuerdas: Acero• Color del producto: Madera• Longitud de cuerdas: 63.4 cm• Material de cuello: Nato• Material de diapasón: Rosewood• Material de puente: Rosewood• Material lateral: Meranti• Material superior: Abeto• Material trasero: Meranti• Profundidad de cuerpo (min): 9.6 cm• Profundidad de cuerpo (máx.): 11.6 cm• Tipo: Acoustic guitar• Tipo de cuerpo: Popular",
    },
    {
        id: 3,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/93f1a8bf-6d85-43fc-95cf-cd38dd13dbdb_548x548.jpg?v=1637278351",
        nombre: "Amplificador CODE412 MARSHALL",
        precio: 8070,
        stock: 20,
        category: "Amplificador",
        descripcion: "La magia clásica de Marshall y la innovación de vanguardia se combinan en la serie CODE y este gabinete en ángulo de 4x12 y 200W no es una excepción.\nDiseñado para el CODE100H, el CODE412 TM está equipado con altavoces personalizados especialmente diseñados para administrar la variedad de tonos disponibles en los amplificadores CODE.\n4 Bocinas Custom Voiced de 12",
    },
    {
        id: 4,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/76053413-831d-4b50-b0b3-7d9c1d091f3d.jpg?v=1637292591",
        nombre: "Bateria MAPEX tornado 5 pzas  TND5254TCDR",
        precio: 13085,
        stock: 25,
        category: "Bateria",
        descripcion: "Batería Serie Tornado 5 pz• Color: Burgundy• El set Mapex Tornado es un juego de batería completo con todo el hardware incluido, que ofrece accesibilidad y facilidad de montaje para el primer set de un baterísta sin sacrificar la calidad del sonido.• Las carcasas de álamo tienen el borde del cojinete Mapex SONIClear que hace que la afinación sea simple mientras que le da a la batería mucho tono.• El bombo de 22 ofrece unos graves contundentes, mientras que los toms de tamaño completo brindan una gran potencia para un gran sonido de tom.",
    },
    {   
        id: 5,     
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/659d44ed-739b-4097-8b4b-a454faa858ce.jpg?v=1637293053",
        nombre: "Baterìa Road Show RS584-C-707",
        precio: 11940,
        stock: 30,
        category: "Bateria",
        descripcion: "Baterìa Road Show 4 Piezas RS584-C-707\nColor: Bronze Metallic.\nHecha con 9 capas de madera poplar acabado en mica.\nMedidas: Toms 10'x07', Piso 14'x10', Tarola 13'x5', Bombo 18'x12'.\nIncluye paquete de Hardware, banco, baquetas.",
    },
    {
        id: 6,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/4f0c6229-c01a-43bb-adbf-feb34b5b2821_438x438.jpg?v=1637327673",
        nombre: "Amplificador guitarra ENVOY 110",
        precio: 7485,
        stock: 35,
        category: "Amplificador",
        descripcion: "Potencia: 40 W. Configuración de altavoces: 1 altavoz de 10 Blue Marvel.2 canales: Clean y Lead.3 Band EQ por canal.Conmutador Modern/Vintage voicing en canal Clean.Conmutador High Gain/Modern/Vintage Voicing en canal Lead.Conector de pedal.",
    },
    {
        id: 7,
        img: "https://cdn.shopify.com/s/files/1/0312/0798/1101/products/19d91525-40f8-4208-b112-344eeb93d5c3_85deff30-7201-4105-a10c-dc743d297ddc_1200x1200.jpg?v=1637865761",
        nombre: "Guitarra ALVAREZ acústica AD60-12-EXP",
        precio: 6920,
        stock: 40,
        category: "Guitarra_Acustica",
        descripcion: "Serie Artista AlvarezMadera superior Abeto A + Sitka macizoFondo y aros de madera CaobaForma AcorazadoCuello Caoba, 50/50 acabado semi brillanteSistema de arriostramiento FST2Puente Laurel indio de dos niveles / palo de rosaDiapasón Laurel indio / Palisandro con incrustación de traste 12Tuerca y silla de montar Hueso real",
    },
    {
        id: 8,
        img: "https://www.mrcdinstrumentos.com.mx/shared/productos/15772/0145212550-01.jpg",
        nombre: "Guitarra Fender Player Telecaster",
        precio: 15000,
        stock: 45,
        category: "Guitarra_Electrica",
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 9,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 9",
        precio: 130,
        stock: 50,
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 10,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 10",
        precio: 140,
        stock: "55",
        descripcion: "Esta es la descripcion de un objeto",
    },    
    {
        id: 11,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 11",
        precio: 150,
        stock: 60,
        descripcion: "Esta es la descripcion de un objeto",
    },
    {
        id: 12,
        img: "https://via.placeholder.com/150",
        nombre: "Nombre del producto 11",
        precio: 160,
        stock: 65,
        descripcion: "Esta es la descripcion de un objeto",
    }

]